-- Thanks to Quartz.NET for this script
-- Link: https://github.com/quartznet/quartznet/blob/main/database/tables/tables_sqlServer.sql

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[QRTZ_TRIGGERS] DROP CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS] DROP CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_CALENDARS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_CALENDARS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_CRON_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_CRON_TRIGGERS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_BLOB_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_BLOB_TRIGGERS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_FIRED_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_FIRED_TRIGGERS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_PAUSED_TRIGGER_GRPS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_SCHEDULER_STATE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_SCHEDULER_STATE];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_LOCKS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_LOCKS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_JOB_DETAILS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_JOB_DETAILS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_SIMPLE_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_SIMPROP_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS];

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[QRTZ_TRIGGERS];

CREATE TABLE [dbo].[QRTZ_CALENDARS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [CALENDAR_NAME] [nvarchar] (200)  NOT NULL ,
  [CALENDAR] [varbinary] (max) NOT NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_CRON_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [CRON_EXPRESSION] [nvarchar] (120)  NOT NULL ,
  [TIME_ZONE_ID] [nvarchar] (80) 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_FIRED_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [ENTRY_ID] [nvarchar] (140)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [INSTANCE_NAME] [nvarchar] (200)  NOT NULL ,
  [FIRED_TIME] [bigint] NOT NULL ,
  [SCHED_TIME] [bigint] NOT NULL ,
  [PRIORITY] [int] NOT NULL ,
  [STATE] [nvarchar] (16)  NOT NULL ,
  [JOB_NAME] [nvarchar] (150)  NULL ,
  [JOB_GROUP] [nvarchar] (150)  NULL ,
  [IS_NONCONCURRENT] [bit] NULL ,
  [REQUESTS_RECOVERY] [bit] NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_SCHEDULER_STATE] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [INSTANCE_NAME] [nvarchar] (200)  NOT NULL ,
  [LAST_CHECKIN_TIME] [bigint] NOT NULL ,
  [CHECKIN_INTERVAL] [bigint] NOT NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_LOCKS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [LOCK_NAME] [nvarchar] (40)  NOT NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_JOB_DETAILS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [JOB_NAME] [nvarchar] (150)  NOT NULL ,
  [JOB_GROUP] [nvarchar] (150)  NOT NULL ,
  [DESCRIPTION] [nvarchar] (250) NULL ,
  [JOB_CLASS_NAME] [nvarchar] (250)  NOT NULL ,
  [IS_DURABLE] [bit] NOT NULL ,
  [IS_NONCONCURRENT] [bit] NOT NULL ,
  [IS_UPDATE_DATA] [bit] NOT NULL ,
  [REQUESTS_RECOVERY] [bit] NOT NULL ,
  [JOB_DATA] [varbinary] (max) NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [REPEAT_COUNT] [bigint] NOT NULL ,
  [REPEAT_INTERVAL] [bigint] NOT NULL ,
  [TIMES_TRIGGERED] [bigint] NOT NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [STR_PROP_1] [nvarchar] (512) NULL,
  [STR_PROP_2] [nvarchar] (512) NULL,
  [STR_PROP_3] [nvarchar] (512) NULL,
  [INT_PROP_1] [int] NULL,
  [INT_PROP_2] [int] NULL,
  [LONG_PROP_1] [bigint] NULL,
  [LONG_PROP_2] [bigint] NULL,
  [DEC_PROP_1] [numeric] (13,4) NULL,
  [DEC_PROP_2] [numeric] (13,4) NULL,
  [BOOL_PROP_1] [bit] NULL,
  [BOOL_PROP_2] [bit] NULL,
  [TIME_ZONE_ID] [nvarchar] (80) NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_BLOB_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [BLOB_DATA] [varbinary] (max) NULL 
) ON [PRIMARY];

CREATE TABLE [dbo].[QRTZ_TRIGGERS] (
  [SCHED_NAME] [nvarchar] (120)  NOT NULL ,
  [TRIGGER_NAME] [nvarchar] (150)  NOT NULL ,
  [TRIGGER_GROUP] [nvarchar] (150)  NOT NULL ,
  [JOB_NAME] [nvarchar] (150)  NOT NULL ,
  [JOB_GROUP] [nvarchar] (150)  NOT NULL ,
  [DESCRIPTION] [nvarchar] (250) NULL ,
  [NEXT_FIRE_TIME] [bigint] NULL ,
  [PREV_FIRE_TIME] [bigint] NULL ,
  [PRIORITY] [int] NULL ,
  [TRIGGER_STATE] [nvarchar] (16)  NOT NULL ,
  [TRIGGER_TYPE] [nvarchar] (8)  NOT NULL ,
  [START_TIME] [bigint] NOT NULL ,
  [END_TIME] [bigint] NULL ,
  [CALENDAR_NAME] [nvarchar] (200)  NULL ,
  [MISFIRE_INSTR] [int] NULL ,
  [JOB_DATA] [varbinary] (max) NULL 
) ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_CALENDARS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [CALENDAR_NAME]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_FIRED_TRIGGERS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [ENTRY_ID]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_SCHEDULER_STATE] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [INSTANCE_NAME]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_LOCKS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_LOCKS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [LOCK_NAME]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPROP_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_TRIGGERS] WITH CHECK ADD
  CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY];

ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [dbo].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;

ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [dbo].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;

ALTER TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [dbo].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;

ALTER TABLE [dbo].[QRTZ_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [dbo].[QRTZ_JOB_DETAILS] (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  );
